### ISSUE TITLE
Require PHP 7.1 for Yii 2.1

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#11397]
## Decision

Update to PHP 7.1.

## TODO

- [x] Install APCu via travis instead of APC: https://github.com/yiisoft/yii2/pull/14505
- [x] Drop memcache (w/o D) support.
- [x] Use null coalesce: https://github.com/yiisoft/yii2/pull/16270
- [x] Remove old PHPUnit polyfills: https://github.com/yiisoft/yii2/pull/14506
- [x] Remove intl polyfills: https://github.com/yiisoft/yii2/pull/16273#pullrequestreview-119708556

## Original issue

Currently only php 5.6, 7 and 7.1 are supported

http://php.net/supported-versions.php

php 5.5 is in security-only support and will reach end of life very soon, while php5.6 will enter security-only support next year. Probably yii 2.1 will take around a year to develop, by that time the entire php5 branch will be obsolete.

Today ubunt 16.04 will be released which includes php7 as the default version and its an LTS so we can expect a lot of server providers to switch to it an offer php7 effortlessly during the next months.

Requiring php7 for yii2.1 can be very useful
- code generation in gii which can take full advantage of the type hintings.
- views and controllers can be simplified a lot with the `use` groups
- Interally yii2 has many unit tests and has a good dependency injection container, both of them can be benefited by the anonymous classes.
- Yii security class can benefit a lot of the new random generators.

I propose to make a poll using emoji's. I will post 3 options bellow and any reaction to them (:+1: :-1: etc) count as a vote for that option. That way someone can vote for more than one option.

**Comment by Faryshta** [comment]
keep minimal version at php 5.5

**Comment by Faryshta** [comment]
php 5.6 for minimal version required for yii2.1

**Comment by Faryshta** [comment]
php 7.0 for minimal version required for yii2.1

**Comment by mdmunir** [comment]
Its depend on when 2.1 stable version released. I am pessimistic it can be done in early next year :D.
depend on what default php version of `debian` and `CentOS`.

**Comment by samdark** [comment]
Ubuntu LTS this summer is going to ship PHP 7 by default.

**Comment by Faryshta** [comment]
@samdark actually it just got released today http://releases.ubuntu.com/16.04/

**Comment by samdark** [comment]
Oh! Great.

**Comment by kavitama** [comment]
I remember when we discussed the 2.0 minimum and at that time we were "cautious" and stick with 5.4 that became obsolete before YII2 was "spread out".
I believe php7 is "the minimum" we can expect to go with and take advantage of speed and new functions that will boost YII

**Comment by Faryshta** [comment]
thats another very valid point @kavitama.

Yii2 took a whilte to get people migrate to it from Yii1 or other frameworks. We need to take into account the time it will take to get it developed + the time it will take to get people migrate to it.

**Comment by Sammaye** [comment]
TBH since Yii2 is already compatible with PHP7 it is reasonable to say that most code written for Yii2 will only have some oddities (like the use of `list()`). So the transition time between PHP 5.6 and 7 is very small.

I think this thread is vague for one. As I said Yii2 is PHP7 compat, so what would change by making PHP7 the min version? The only real thing is if Yii2 starts using PHP7 specific stuff such as autoloading of functions in namespaces.

**Comment by tunecino** [comment]
https://github.com/yiisoft/yii2/issues/7936 should also be considered to not having to drop v2.1 when PHP 7.1 or 7.2 is released.

**Comment by samdark** [comment]
2.1 isn't going to be such a huge update that it's impossible to update apps with some code changes. We aren't going to do 1.1 → 2.0 again. It will be 2.0 → 2.1 → 2.2 → ... → 3.0 i.e. incremental breakages.

**Comment by cebe** [comment]
The minimum required version has to be determined by technical requirements. If we find that using features that are in a higher version, we can bump version requirement. If we do not use any of the features, the min version will stay.

That means, if we bump to 5.5 or 5.6, what are the features we are going to use?

- http://php.net/manual/en/migration55.new-features.php
- http://php.net/manual/en/migration56.new-features.php

I am for 5.6 because it adds some cool things that can improve many parts of the framework, such as `::class` notation, `..$args` function argument unpacking, `yield` generators, etc...

But if we bump to php7 that would mean a lot of framework concepts should be thought through from ground up considering the newly available languages features. Imo that is out of scope for a 2.1 but rather something for a 3.0.

**Comment by samdark** [comment]
7.0 is for security features only but it's from "nice to have" category since we're already covered that via other means.

**Comment by Faryshta** [comment]
PHP7 has a lot of feature we can use. 

* The return type hintings which can be very useful for relations, models, validators, etc.

* The code generated by Gii can take full advantage of this and generate php7 style code inmediately.

* Anonymous classes can help a lot with dependency injection, configurations and unitary testing.

* Use groups can simplify the code generated by gii and it can also be very useful when dealing with controllers, views and assets. For example views with a several widgets from the `yii\bootstrap` namespace.

* scalar type hints are very useful for controllers and models, and gii can generate this hints too. For example

```php

use common\models\post\{Post,Category,Comment};

PostController extends Controller
{
    public function actionView(int $id): string
    {
        $model = $this->findModel($id);
        // etc
    }

    public function findModel(int $id): Post
    {
           if (null === ($post = Post::findOne($id))) {
               return $post;
           } else {
               // exception
           }
     }
}
```

This code is not only easier to read for humans, its also much easier to read for IDE's https://blog.jetbrains.com/phpstorm/2015/11/phpstorm-10-is-released-php-7-support-interactive-debug-console-repl-dataflow-analysis-phpunit-5-support-and-more/

**Comment by samdark** [comment]
> The return type hintings which can be very useful for relations, models, validators, etc.

Nope since they do not support nulls.

**Comment by Faryshta** [comment]
@samdark

```php
public function getOrders(): ActiveQuery
{
    return $this->hasMany(Order::class, ['customer_id' => 'id']);
}
```

Doesn't need a `null` case.

**Comment by samdark** [comment]
Yes. I'm talking about `findOne()` and `one()` like methods.

**Comment by Faryshta** [comment]
yup those methods can't take the advantage for return typehints, but those are much lower cases.

**Comment by cebe** [comment]
@Faryshta most of what you say does not require the framework itself to require php7. The framework can be PHP7 aware but still be compatible with php5.6. That means if you want to use php7 typehints in your application code, you are free to do that.

**Comment by Razzwan** [comment]
There will always be people who try to slow down the development. I believe our way to be ahead. That's why I'd like to at least php7.0.

**Comment by mikehaertl** [comment]
IMO we should not bump requirements to PHP 7 unless there's really good reason to do so. The only acceptable reason I could think of is a boost in performance. I doubt that there's any PHP7-only feature that would have such a great effect - note I'm only talking about framework code here.

So my vote goes for 5.6 to not lock out too many developers. Yii is a framework and as such should not put as few constraints on the developer as possible.

**Comment by duruitang** [comment]
PHP 7 is so fast and  usable! See http://www.slideshare.net/laruence/php7-for-its-best-performance
![image](https://cloud.githubusercontent.com/assets/13196890/14911326/536e90d6-0e27-11e6-9f62-c0e66bcd33e3.png)
![image](https://cloud.githubusercontent.com/assets/13196890/14911339/63a80c2a-0e27-11e6-8510-ffe3a4145027.png)

**Comment by Sammaye** [comment]
Zend 3 is a massive improvement even without using PHP7 features. I mean
PHP can actually work in daemon mode (though still not a good idea)

**Comment by cebe** [comment]
you can have php7 perfomance without forcing other to use php7, so that is not an argument in the discussion here. of course we support php7, the question is only if we should require it.

**Comment by Faryshta** [comment]
@cebe another idea can be to have two branches. 2.1 and 2.7 for example with 2.7 requiring php7 and 2.1 php5.6 and then let composer figure out which one install depending on the server

**Comment by cebe** [comment]
that sounds complicated and confusing.

**Comment by Sammaye** [comment]
Well, that's the case I said earlier in the discussion. What exactly would
it mean for Yii2 to move to PHP7 only? It seems that answer is vague for
one.

It seems from your previous comments that 5.6 adds most of the features
that would actually change the framework

**Comment by Faryshta** [comment]
@Sammaye the best features in php7 are return type hints and anonymous classes. as @samdark mentioned there are many securities upgrades too but those are mostly supported already for yii2.

 @cebe why confusing?

**Comment by Sammaye** [comment]
Though as discussed earlier by you and samdark it seems that type hinting
was questionable in many parts of the framework atm which means the case of
it might be questionable

**Comment by duruitang** [comment]
I think @cebe got the point. `Of course Yii2 support php7, the question is only if we should require it.`
According to http://php.net/supported-versions.php , I suggest that Yii2.1 should NOT support php 5.4 && php 5.5 anymore, for more security. Yii should always be `The Fast, Secure and Professional PHP Framework`, via www.yiiframework.com.

**Comment by duruitang** [comment]
![image](https://cloud.githubusercontent.com/assets/13196890/14913789/0071cb44-0e38-11e6-9a6e-9969c30c791b.png)

**Comment by samdark** [comment]
According to current voting, it's a good idea that:

- Yii 2.1 require PHP 5.6.
- Yii 2.1 support PHP 7+.

**Comment by Faryshta** [comment]
@samdark sounds good.

How about the idea for a php7 branch and see if we can release it someday as 2.2 or something else?

Should I make a new discussion about it?

**Comment by samdark** [comment]
It depends very much on when we're going to release 2.2. 5.6 has more than 2 years of lifetime left. 7.0 life span is shorter than 5.6 one so I guess it could be either still 5.6 if 2.2 is going to be released in a year or so or 7.1 otherwise.

![image](https://cloud.githubusercontent.com/assets/13196890/14913789/0071cb44-0e38-11e6-9a6e-9969c30c791b.png)

**Comment by Sammaye** [comment]
You cloud argue that specific PHP7 functionality should be skipped until they release an LTS version like PHP5.6 since the lack of long shelf life could mean that changes might be coming

**Comment by Faryshta** [comment]
@Sammaye php5.6 is not an LTS, its a rare exception that mostlikely won't happen again.

@samdark by then it will be security only and even if 2.2 uses php5.6 we can still have a php7 branch and php7 releases

**Comment by samdark** [comment]
What's the goal of php7 branch if code will be the same? We aren't going to support 2 different branches at the same time.

**Comment by Faryshta** [comment]
i can provide help with the php7 branch and the code won't be the same, i truly think we can take a lot of advantage of the scalar typehints, return typehints and anonymous classes

**Comment by duruitang** [comment]
@Faryshta I think we should vote for @samdark 's point. The Yii2 official team should be focus on one branch. Php7 lovers can fork Yii2.1 as unofficial php7 repository , and all of php7 lovers can pull requests for it.

**Comment by duruitang** [comment]
I watched a php conference hold in China, One of the php official team members @Laruence told us that php7 support strongly-typed variables, but he suggest we do not use it unless it has to.

**Comment by Razzwan** [comment]
@samdark > What's the goal of php7 branch if code will be the same? We aren't going to support 2 different branches at the same time.

Support branch 7.0 is not required. There will be a similar code with the same tests, but using the power of php7. Take pull request in php7 branch will simply just need to make sure that the code does the same thing. It's so simple - to create a branch.

If a community activity will focus mainly on it, that fact will be much more eloquent than the current debate, and then we can reconsider the decision taken by. And now, I really like the idea of ​​branches, which will require php7 and intend to take an active part in its support. Perhaps due to the use of strong typing, will be able to improve the performance of proper framework.

**Comment by samdark** [comment]
@Razzwan what's the goal of that branch if code does the same thing except requiring PHP7?

**Comment by samdark** [comment]
Done https://github.com/yiisoft/yii2/commit/c5efe32c2804ebef570b61eca03d1d577eb786b3

**Comment by Faryshta** [comment]
> what's the goal of that branch if code does the same thing except requiring PHP7?

It won't be the same code nor do the 'same' it will just pass the unit tests the same way. For example dependency injection can be enhanced a lot using anonymous classes, the `yii\base\Security` class can be simplified.

Generators like gii will be able to produce return types, group `use` declarations, better type hinting and the code will be easier to read and debug for typehings.

**Comment by cebe** [comment]
@Faryshta most of what you say can be used without the whole framework to require php7.

- for DI, not sure what you want to do with anonymous classes, please open an issue about this if you want to discuss that topic and provide some examples.
- `yii\base\Security` already uses the methods available in PHP 7 if you run PHP 7.
- Gii could have a flag that allows generating code including typehints, that flag shoud be added anyway as not everyone wants to use strict type hinting.

**Comment by tom--** [comment]
I am using PHP 7 in my Yii 2.0-based project. It's great. All the good things people say about PHP 7 are correct as it applies to my work.

But I can't imagine that the Yii Framework will be better for me if it requires PHP 7 for itself.

**Comment by Razzwan** [comment]
@samdark 
> Strong typing has nothing to do with performance at all
Than you can justify this view? 

The main reason slow php - is the lack of strong typing. After the processing of unknown data type wasted a huge pile of resources. From the assumption that this problem can be solved by using strong typing, where possible. Those. theoretically, it is possible to compete with other programming languages for speed.

**Comment by cebe** [comment]
the same php engine is not getting any faster if you use more type annotations. What makes you think that?

**Comment by tom--** [comment]
It would be PHP's job to realize any performance gain for scripts that use type hints and declarations. [They tried and it didn't work.](https://youtu.be/qbRRrTkZ5Mo?t=16m13s)

And you can skip forwards to [Zeev's comments on hints/declarations here](https://youtu.be/qbRRrTkZ5Mo?t=26m29s)

**Comment by Razzwan** [comment]
@cebe 
> the same php engine is not getting any faster if you use more type annotations. What makes you think that?

C - strictly tipizorovanny language. Php is written in C. When I do not use strong typing, it turns on a mechanism to automatically identify the type of the variable. When we use strong typing - this mechanism is skipped. Those code runs faster. Where I am wrong?

**Comment by rob006** [comment]
@Razzwan http://stackoverflow.com/questions/32940170/are-scalar-and-strict-types-in-php7-a-performance-enhancing-feature

**Comment by cebe** [comment]
@Razzwan C is mostly faster than PHP because it is compiled and not because of its typing system. PHP is an interpreted language, which means (simplified) it will be compiled each time it is executed instead of once. Using strict types in PHP will not make it as fast as C.

**Comment by Razzwan** [comment]
I read the response to snfasf and it says that strong typing can speed up code after a new kernel update. If we use it now, we will get all the benefits right away as soon as they appear.

**Comment by tom--** [comment]
Possibly of interest in this context.

https://wiki.php.net/rfc/nullable_types#voting_choices

**Comment by alirafiq** [comment]
i am using wamp, php 5.6 and Yii2. I run my application on virtualhost , it works fine , when i am trying to run application without virtual host each route give me 400 bad request ...
after lots of setting and configuration but not resolved, , then I installed php7 .. It was working fine..
so Yii2 works well on php7.

**Comment by tom--** [comment]
@alirafiq i don't know why you got errors without vhost or why they went away with php7.

yes, yii2 works very well on php7. we have had no problems at all and we will be upgrading to 7.1 soon.

**Comment by SamMousa** [comment]
In my opinion there is also the responsibility of helping developers make sane choices.

If you require a higher PHP version then a new developer will make a better choice. If they are forced to develop for older PHP version they will need to discuss that upstream, since that is the issue.

This is basically the same discussion everywhere, remember IE6? 
We should definitely try to push developers to newer versions of PHP as long as they are stable. If hosting providers don't over it then they will lose a competitive edge; if some linux distributions don't offer it then they will lose market share.

I definitely vote 7.1 / 7.0 as a minimum.

**Comment by tom--** [comment]
I firmly feel there's only one good reason to continue to use PHP 5.* – to keep alive apps that are no longer maintained. That doesn't apply to any use of Yii 2.1 so I advocate requiring 7.1 (or whatever is current when 2.1 is released).

To someone who objects that "my hosting provides only 5.6" I would reply, "that's terrible hosting, spend your money on a provider that deserves your business."

The BC issues 5.* → 7.* are not hard to overcome. And from 7.0 to 7.1 there's basically none.

**Comment by yyxx9988** [comment]
![Dependency Status](https://cloud.githubusercontent.com/assets/13196890/14913789/0071cb44-0e38-11e6-9a6e-9969c30c791b.png)

I vote 5.6

**Comment by Sammaye** [comment]
PHP7 is still new in many ways and is not trusted for a wide number of applications. 5.6 is a good line for a base requirement

**Comment by SamMousa** [comment]
@Sammaye Any source for your statement?
I know many frameworks don't require it, but afaik it isn't because they don't trust it...

**Comment by tom--** [comment]
7.0 was released 16 months ago and has had 17 patch releases. That's not very new.I haven't heard that PHP 7 is not trusted. The only thing to distrust that I can imagine is migrating an old app. But that's a problem of app testing, not of PHP.On Mar 31, 2017 10:51 AM, Sam Millman <notifications@github.com> wrote:PHP7 is still new in many ways and is not trusted for a wide number of applications. 5.6 is a good line for a base requirement

**Comment by mikehaertl** [comment]
I would argue that it's never good to put constraints on other developers, just because "we know what's good for you". We should not assume that they are stupid. Of course, they'll know, that they should try to use PHP 7.x if possible. But, you know, reality sometimes isn't perfect. You have to live with compromises and it could happen that they have to work with an older PHP versions for different reasons.

You can still use PHP 7.x even if the min requirement is 5.x. So just because some will always use PHP 7 with Yii 2.1 is this a good reason to put this as constraint to everyone else? 

Shouldn't a good framework instead be as open and versatile as technically possible? I'd say we should rather focus on the technical aspects. To me the main questions are,  will any Yii 2.1 app be

 * slower?
 * harder to maintain?
 * less stable?

just because it still supports 5.6 (or even < 5.6)? I've not seen a good argument yet that any of this is the case. And even if there is, we could try to autodetect critical PHP 7 features and support both.

**Comment by SamMousa** [comment]
That argument doesn't really hold; if we don't put constraints on others,
we put them on ourselves. Since we can't benefit from new features.

So then it is okay for them to constrain us but not the other way around?
;-)

**Comment by mikehaertl** [comment]
> Since we can't benefit from new features.

But which are those in regard to the 3 points I mentioned above? I mean which features that are **only available in PHP 7**  but **not in PHP 5.x** makes an app:

* faster
* or easier to maintain
* or more stable?

I talk about significant differences here. So a 0.3% perfomance increase due to some BC breaking syntax change should not really count as argument.

**Comment by SamMousa** [comment]
https://kinsta.com/blog/php-versions/

The performance of course is nice but not a big argument, we don't need to
require php 7 for that.

For me personally its things that make my life easier:
- null coalesce
- ::class
- spaceship operator
- built-in security functions


In my opinion there are very few to no arguments at all for not running
php7.

As a contributor I will contribute less if I have to account for ancient
things. Which is php 5.6 in 1 year...

**Comment by rob006** [comment]
Dropping PHP5 will make framework easier to maintain. Having `Throwable` will simplify error handling (see https://github.com/yiisoft/yii2/issues/12619#issuecomment-253473027) and security component. PHP5 has also some bugs and limitations (see https://github.com/yiisoft/yii2/pull/12929#issuecomment-260129127) which makes some things harder (or even impossible) to do. 

Separate thing is PHP community, which we can't just ignore. General trend is dropping PHP5 - PHPUnit 6 requires PHP7, [Symfony and Laravel has plans to drop PHP5 support in this year](https://murze.be/2016/12/laravel-5-5-will-require-php-7-0/). Supporting PHP5 will limits us to the tools or dependencies which we can use.

**Comment by samdark** [comment]
Yes. Dependencies are strong argument indeed.

**Comment by tom--** [comment]
> That argument doesn't really hold; if we don't put constraints on others, we put them on ourselves. Since we can't benefit from new features.

This elegantly summarizes the trade-off and extends to using newer dependencies.

One example of this I have been involved with for [more than 5 years](https://wiki.php.net/rfc/csrandombytes) is reliable unpredictable randomness. The framework and apps both need it. The various "polyfills" for what eventually became `random_bytes()` and `random_int()`, such as they existed depending what year we're talking about, were more-or-less unsatisfactory in my opinion. So Yii 2 has this [nasty chunk of code](https://github.com/yiisoft/yii2/blob/master/framework/base/Security.php#L449) that's very hard to test.

This example shows that Yii, and apps that use, it are more secure and stable if we have PHP 7 and don't require this code. Also that we create work for ourselves by trying to support old platforms.

There are several examples like this elsewhere in `Security` component. The less such code we need, the smaller the attack surface Yii presents, where "attack surface"  is just fancy security words for "a volume of code that we can't prove has no bugs."

**Comment by tom--** [comment]
@mikehaertl My previous comment is an example of "putting constraints on ourselves." But also responds to your challenge as an example of something more stable and easier to maintain in PHP 7.

Another thing that's a really big deal is that PHP 7's allows us to handle PHP errors as exceptions. This can radically simplify some problems and make them much easier, or even possible, to test.

I believe type declaration has reduced the rate at which we (me and my colleagues) write bugs. Since PHP 7.1 has also nullable type and void return declarations, I think the framework can start to use them and the bug rate will go down even more.

So yes, I think 7 is important for code quality, stability, and maintainability.

**Comment by tom--** [comment]
And finally, something in 7 that I just like and that few have commented on is that `??` gives PHP usable [map](http://thefsb.tumblr.com/post/127724076940/if-ternary-switch-or-map) control structure:

    ['a' => 5, 'b' => 8, 'x' => 'y'][$var] ?? 'default'

**Comment by SamMousa** [comment]
I love that null coalesce operator :D

**Comment by cebe** [comment]
> I believe type declaration has reduced the rate at which we (me and my colleagues) write bugs. Since PHP 7.1 has also nullable type and void return declarations, I think the framework can start to use them and the bug rate will go down even more.

I think this means that if we bump to PHP 7 we must bump for PHP 7.1.

**Comment by takobell** [comment]
FWIW, we're requiring PHP 7 on the next version of [Craft](https://craftcms.com/3) (built on Yii 2).  For some real world statistics, we're showing 28% of existing Craft installs are running PHP 7.x+.  25.5% on PHP 7.0 and 2.5% on PHP 7.1.

**Comment by samdark** [comment]
Thanks for stats.

**Comment by Faryshta** [comment]
more stats https://seld.be/notes/php-versions-stats-2016-2-edition

php7.0 is expected to surpass php5.6 already.

**Comment by samdark** [comment]
Zend Framework is going to require 7.1: http://tinyletter.com/mwopzend/letters/zend-framework-community-news-for-the-week-of-2017-04-20

**Comment by samdark** [comment]
So overall it seem like a no-brainer to me because supporting 7.0 and less would add more and more burden. PHPUnit is the first signal.

**Comment by SamMousa** [comment]
Agree 100% :-)

**Comment by Faryshta** [comment]
i think we should start by editing the https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md to set the new standards.

for example. is `void` mandatory when dealing with a method that doesn't return anything?

must we change all declarations of `list()` to `[]`?

another topic would be: since we are bumping php requirement should we also bump requirement for all the libraries that can support it? such as requiring phpunit 6?

**Comment by samdark** [comment]
> is void mandatory when dealing with a method that doesn't return anything?

No since from past years these are often start to return $this for chained calls later.

> must we change all declarations of list() to []?

We can and I think we will.

> another topic would be: since we are bumping php requirement should we also bump requirement for all the libraries that can support it? such as requiring phpunit 6?

Yes.

**Comment by tom--** [comment]
I prefer PHP over phpDocumentor 2. So I would use `void` when it describes the truth. You can (should, *must!*) change it if the method's return changes, just as you would the docblock.

Btw, I started removing docblock lines from my own files when they supply no more information than the function declaration.

**Comment by samdark** [comment]
Decision is to update to PHP 7.1. Started it.

**Comment by SamMousa** [comment]
@samdark Is the goal to at some point in the future start each file with `declare(strict_types=1);`?
And will there be scalar type hints added everywhere where PHPDoc is used now?

**Comment by samdark** [comment]
Yes, I think so.

**Comment by spinitron** [comment]
I think it's important to use strict types if scalar argument and return declaration is used. This has interesting implications, for example: Don't call a function with a scalar type argument *from* a file that is not in strict mode.

But I think it's better to start another issue or wiki or something to discuss coding practices in the post PHP 7.1 era.

**Comment by tom--** [comment]
I think it's important to use strict types if scalar argument and return declaration is used. This has interesting implications, for example: Don't call a function with a scalar type argument *from* a file that is not in strict mode.

But I think it's better to start another issue or wiki or something to discuss coding practices in the post PHP 7.1 era.

**Comment by samdark** [comment]
> Don't call a function with a scalar type argument from a file that is not in strict mode.

Why?

**Comment by tom--** [comment]
@samdark I wrote about this here https://youtrack.jetbrains.com/issue/WI-31785

**Comment by Faryshta** [comment]
@tom-- i don't think thats doable for a framework specially because the developer using the framework might simply write non-strict files.

and yii2 has no way to know if a method is called from a non-strict file.

at best this needs to be addressed in php core, php7.2 is about to enter beta-freeze so maybe for 7.3

**Comment by tom--** [comment]
@Faryshta Yes, you're absolutely right. Yii cannot fix this, nor can it prevent users' calls of Yii's functions from making this mistake. I'm just suggesting that Yii can avoid making this mistake itself when it calls a function. And in doing so, and by adopting it into the code style, can help educate others about this particular hazard.

I would prefer if PHP would fix this but, for political reasons, I don't see much chance. I certainly don't want to propose it. Real big shots in internals had to concede this in the compromise that required to get what we have now.

While it's not good, it's not a disaster. And you're right that we can't fix it. But we can do our bit in Yii 2.1 to mitigate it.

Tbh, I really brought this up as an example of a style guide question that we could consider.

**Comment by yacine-harbi** [comment]
"Debian's default PHP version (currently 7.0)"

The latest Debian (9 - stretch) released a week ago is out then ?

**Comment by samdark** [comment]
Yes. We can't do anything about it. 7.0 support timeline is too bad for us.

**Comment by yacine-harbi** [comment]
To put it in perspective, Laravel 5.5 will require PHP 7.0 and will be the next LTS.
Frankly, I'm quit disappointed, I chose Yii2 against laravel exactly for this reason.

**Comment by yyxx9988** [comment]
@yacine-harbi PHP7 has done a good job of compatibility and improved performance, why do you treat new technologies negatively?

**Comment by yacine-harbi** [comment]
I have no intention of starting a flame war, I have tremendous respect for the hard work put into yii2, but for answering your question I'll just say that the real world is not just about shinny new projects and so, it's also about server/admin constraints/eco-system, supporting legacy software, etc.

**Comment by TomaszKane** [comment]
@yacine-harbi ok, but IMHO new frameworks (or new version of frameworks) should use actual technology - not stay behind because some admins can't update PHP version.

**Comment by samdark** [comment]
@yacine-harbi we aren't going to raise requirements for 2.0.x.

**Comment by cebe** [comment]
@yacine-harbi pretty sure 7.1 will soon be available in the debian backports.

**Comment by TomaszKane** [comment]
For now we have https://deb.sury.org/

**Comment by jblac** [comment]
as of right now, 7.x is the only answer here even worth considering.   From the security updates, performance boosts alone it's worth the upgrade.  Then you bring in options like null coalescence, scalar type hints, generator delegation, throwables just to name a few -- and things that I use extensively in our yii2 application.

Any choice but 7.x is a crime against humanity.  php5.6 is past it's acceptable EOL limit, and this is the reason that other frameworks have already made the shift.

**Comment by cebe** [comment]
btw: https://twitter.com/cebe_cc/status/866398230665453568
> Which PHP version are you running your #Yii2 applications on? #php #yii
> - 30% PHP 5.x
> - 33% PHP 7.0
> - 36% PHP 7.1
> -  1% HHVM
> 371 Votes on 21. Mai 2017

**Comment by TomasVotruba** [comment]
This might help to decide: https://gophp71.org/

**Comment by samdark** [comment]
It's already decided but thanks for the link. Added Yii there: https://github.com/TomasVotruba/gophp71.org/pull/3

**Comment by TomasVotruba** [comment]
@samdark Glad to hear that, thanks for the PR!

**Comment by schmunk42** [comment]
The commit https://github.com/yiisoft/yii2/commit/0117459 requires 7.1 - unless reverted, the decision is made 😶

**Comment by haohetao** [comment]
php 7.1 for minimal version required for yii2.1

**Comment by TomaszKane** [comment]
Hm, 7.1 will be supported to 1 Dec 2019, and 7.2 has no (many) cool features http://php.net/releases/7_2_0.php

**Comment by SamMousa** [comment]
Isn't that just security support?
Anyway my point is that it might be a while before we release 2.1 why decide now?

**Comment by TomaszKane** [comment]
Yes and no: http://php.net/supported-versions.php
This is question to core developers, IMHO code is writing now - so now devs uses features from 7.1. Other way, you want to refactor code before release to use enhancements from 7.2?
And it probably better to announced target version now, so people can prepare they hosts to Yii 2.1.

**Comment by samdark** [comment]
Currently it's coded with 7.1 in mind. We can switch to 7.2 if it will give us any advantages.
