### ISSUE TITLE
Have at least basic tests for js

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#12840]
Extracted from #11037.

TODO list (added by @cebe):

- [x] implement basic test setup with example test suite for `yii.validation.js` (#12936)
- [x] make tests run on travis
- [x] add tests for yii.activeForm.js
- [x] add tests for yii.captcha.js (#13160)
- [x] add tests for yii.gridView.js (#13230)
- [x] add tests for yii.js (#13316)
- [x] add tests for yii.validation.js (#12936)

**Comment by dynasource** [comment]
yes, this should be implemented. A few months ago, I created a local testsuite based on Mocha & Node.js for speed (instead of phantom). Its not easy to setup, but its possible. Perhabs also possible for githubs Jenkins/Travis?

**Comment by cebe** [comment]
If someone wants to work on this, that would be awesome!

**Comment by dynasource** [comment]
it would be nice to discuss how to implement this properly. Questions to be answered:
* should we use nodejs + jsdom or phantom?
* should we use Mocha?
* should we start with ES5  | Typescript | javascript

If you'd ask me:
* Lets use nodejs + jsdom because of high speed & good support & less error prone thant phantom
* Lets use Mocha (seems to be the most popular at the moment)
* Lets ES5 and transpile at every change into source code (required to be done by the developer)

We could make use of the ES5 'class' system, which makes the code way easy to understand and to split in self contained units, making testing also easier. Of course this is tricky. At every change of the code, the end result has to be transpiled into the source code. Also, the mapping files have to be generated so viewing in Chrome is possible.

One can argue that it is too tricky to do, but on the contrary, if you look at how many bugs we have with JS in our issue tracker, a modular design is really demanded.

**Comment by arogachev** [comment]
@dynasource Good news - I started working on this about week or more ago. You can set me as assignee. Currently I wrote full tests suite for `yii.validation.js`. It's based on Mocha, Chai, Sinon and Leche. Will open PR soon.

As for `yii.validation.js` - there are almost no DOM manipulations. Currently the tests are adapted to run only in browser, but I'm going to swap it with Node / Phantom.

To answer your questions:

> should we use nodejs + jsdom or phantom?

Not sure about that at the moment.

> should we use Mocha?

I think we should. I investigated this problem before writing tests, have read some articles. Mocha seems to be good choice, but QUnit and Jasmine are reliable too. Personally I'm for Mocha.

> should we start with ES5 | Typescript | javascript

I think we need to use regular JavaScript (ES5) based since the testable code is written in it too. Also the amount of JS code is not so huge.

> We could make use of the ES5 'class'

Did you mean ES6?

**Comment by dynasource** [comment]
great. Im looking foward to your first PR. Lets start with Mocha tests and we will see how we will run these later. Regarding the scripting language. It seemed that I've confused 'classes' with es5's inheritance. Lets follow your suggestions.

**Comment by cebe** [comment]
We have set the basis for javascript testing. Time to add more tests! :)

**Comment by arogachev** [comment]
@cebe I'm going to add more soon.

**Comment by arogachev** [comment]
I think this related [jsdom](https://github.com/tmpvar/jsdom) README section - [jsdom vs. PhantomJS](https://github.com/tmpvar/jsdom#jsdom-vs-phantomjs) can be useful for reading and understanding that jsdom is a good choice for testing jQuery too. jQuery docs in the [NPM package](https://www.npmjs.com/package/jquery#node) mention it too

**Comment by schmunk42** [comment]
The Dockerized Testing would come in handy for this.
We could use "a real browser" through a selenium-container.
