### ISSUE TITLE
Add more features to elasticsearch

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#1313]
To make elasticsearch support complete.

Moved these from #1295 as we can easily add them later and they are nice to have.

- [x] make use of native optimistic locking support
- [x] implement [versioning](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-index_.html#index-versioning)
- [ ] api to retrieve parents and children (see also https://github.com/yiisoft/yii2/issues/5758#issuecomment-65063787)
- [x] make index and type available in `instantiate` (#2289)
- [x] implement updateAllCounters(), see for details elasticsearch/elasticsearch#1583
- [ ] implement copy() and move() as PK change is not supported
